version: '2.2'

services:
 
  mapserver:
    image: cproj
    build: .
    environment:
      MS_DEBUGLEVEL: "5"
      MAPSERVER_CATCH_SEGV: "1"
    volumes:
      - ./docker/mapfile:/map:ro
      # - ./docker/proj:/usr/share/proj

  mapcache:
    image: camptocamp/mapcache:1.6
    volumes:
      - ./docker/mapcache:/etc/mapcache:ro
    volumes_from:
      - mapserver
    links:
      - mapserver:mapserver

